## Installation Numpy

In [ ]:
%pip install numpy

## Import Numpy

In [6]:
import numpy as np

In [7]:
print("numpy", np.__version__)

numpy 1.26.4


## Check Packgage Version in Python

In [8]:
# Check the version of the numpy package
print("numpy", np.__version__)

numpy 1.26.4


In [9]:
# # Checking the available methods
print(dir(np))

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals', '_int_extended_ms

In [10]:
print(np.log10(2))
print(np.not_equal(10,10))

0.3010299956639812
False


## Craeting a List in Python

### Creating Int Numpy Arrays

In [11]:
# Creating list python

python_list = [1, 2, 3, 4, 5]
# checking data types
print(type(python_list))
print(python_list)

two_dimensional_list = [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
print(two_dimensional_list)

<class 'list'>
[1, 2, 3, 4, 5]
[[0, 1, 2], [3, 4, 5], [6, 7, 8]]


## Creating Numpy Array Using Numpy

In [12]:
# Creating numpy (Numerical Python) array from python list
numpy_array_from_list = np.array(python_list)
print(type(numpy_array_from_list))
print(numpy_array_from_list)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [13]:
numpy_array_from_list2 = np.array(python_list)
numpy_array_from_list2

array([1, 2, 3, 4, 5])

### Creating Float Numpy Arrays

In [14]:
numpy_array_from_list2 = np.array(python_list, dtype=float)
numpy_array_from_list2

array([1., 2., 3., 4., 5.])

### Creating Boolean Numpy Arrays

In [16]:
numpy_bool_array = np.array([0, 1, -1, 0, 0], dtype=bool)
numpy_bool_array
# Only values different from 0 are considered True, while zero is considered False

array([False,  True,  True, False, False])

### Creating Multidimensional Numpy Arrays

In [18]:
numpy_two_dimensional_list = np.array(two_dimensional_list)
print(type(numpy_two_dimensional_list))
print(numpy_two_dimensional_list)

<class 'numpy.ndarray'>
[[0 1 2]
 [3 4 5]
 [6 7 8]]


## Converting Numpy Array to List

In [19]:
# We can always convert an array back to a python list using tolist()
np_to_list = numpy_array_from_list.tolist()
print(type(np_to_list))
print("One dimensional array: ", np_to_list)
print("Two dimensional array: ", numpy_two_dimensional_list)

<class 'list'>
One dimensional array: [1, 2, 3, 4, 5]
Two dimensional array: [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [20]:
numpy_two_dimensional_list

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Converting Numpy Array From Tuple

In [21]:
# Numpy array from tuple

# Creating tuple in python

python_tuple = (1, 2, 3, 4, 5)
print(type(python_tuple))
print("python_tuple: ", python_tuple)

numpy_array_from_tuple = np.array(python_tuple)
print(type(numpy_array_from_tuple))
print("numpy_array_from_tuple: ", numpy_array_from_tuple)

<class 'tuple'>
python_tuple:  (1, 2, 3, 4, 5)
<class 'numpy.ndarray'>
numpy_array_from_tuple:  [1 2 3 4 5]


In [22]:
numpy_array_from_tuple

array([1, 2, 3, 4, 5])

## Shape of Numpy Array

In [23]:
nums = np.array([1, 2, 3, 4, 5])
print(nums)
print("Shape of nums: ", nums.shape)
print(numpy_two_dimensional_list)
print("Shape of numpy_two_dimensional_list: ", numpy_two_dimensional_list.shape)
three_by_four_array = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])
print(three_by_four_array.shape)

[1 2 3 4 5]
Shape of nums:  (5,)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Shape of numpy_two_dimensional_list:  (3, 3)
(3, 4)


## Data type of Numpy Array

In [25]:
int_lists = [-3, -2, 1, 0, 1, 2, 3]
int_array = np.array(int_lists)
float_array = np.array(int_lists, dtype=float)

print(int_array)
print(int_array.dtype)
print(float_array)
print(float_array.dtype)

[-3 -2  1  0  1  2  3]
int32
[-3. -2.  1.  0.  1.  2.  3.]
float64


## Size of a Numpy Array

In [26]:
numpy_array_from_list.size

5

In [27]:
numpy_two_dimensional_list.size

9

## Mathemetical Operation

### Addition

In [28]:
# Mathmetical Operation

# Addition

print("Original array: ", numpy_array_from_list)
ten_plus_original = numpy_array_from_list + 10
print(ten_plus_original)

Original array:  [1 2 3 4 5]
[11 12 13 14 15]


### Subtraction

In [29]:
print("Original array: ", numpy_array_from_list)
ten_minus_original = numpy_array_from_list - 10
print(ten_minus_original)

Original array:  [1 2 3 4 5]
[-9 -8 -7 -6 -5]


## Multiplication

In [30]:
print("Original array: ", numpy_array_from_list)
ten_times_original = numpy_array_from_list * 10
print(ten_times_original)

Original array:  [1 2 3 4 5]
[10 20 30 40 50]


## Division

In [31]:
print("Original array: ", numpy_array_from_list)
ten_times_original = numpy_array_from_list / 10
print(ten_times_original)

Original array:  [1 2 3 4 5]
[0.1 0.2 0.3 0.4 0.5]


## Modulus

In [32]:
# Modulus: Finding the remainder

print("Original array: ", numpy_array_from_list)
ten_times_original = numpy_array_from_list % 3
print(ten_times_original)

Original array:  [1 2 3 4 5]
[1 2 0 1 2]


## Floor Division

In [33]:
# Floor division: the division result without the remainder

print("Original array:", numpy_array_from_list)
ten_times_original = numpy_array_from_list // 10
print(ten_times_original)

Original array: [1 2 3 4 5]
[0 0 0 0 0]


## Exponential

In [35]:
# Exponential is finding some number the power of another:

print("Original array: ", numpy_array_from_list)
ten_times_original = numpy_array_from_list**2
print(ten_times_original)

Original array:  [1 2 3 4 5]
[ 1  4  9 16 25]


## Converting Types

### Int to Float

In [41]:
numpy_array = np.array([1, 2, 3, 4, 5])
numpy_float_list = numpy_array.astype("float")
print(numpy_float_list)

[1. 2. 3. 4. 5.]


## Float to Int

In [42]:
numpy_float_list.astype("int")

array([1, 2, 3, 4, 5])

## Int to Str

In [45]:
numpy_array = numpy_array.astype("int").astype("str")
print(numpy_array)

['1' '2' '3' '4' '5']


## Dimensional Array